# Generated by Django 3.1.13 on 2023-07-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_merge_20210325_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Competition name')),
                ('pairFinalists', models.BooleanField(blank=True, default=True, verbose_name='Paired Final')),
                ('resultsVisible', models.BooleanField(default=False, verbose_name='Publish results')),
                ('judjes', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Judjes')),
            ],
        ),
        migrations.CreateModel(
            name='PrelimsRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_num', models.IntegerField()),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.competition')),
                ('comp_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dancerole', verbose_name='Dance Role')),
                ('competitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Competitor')),
            ],
            options={
                'unique_together': {('comp', 'comp_num')},
            },
        ),
    ]
