# Generated by Django 3.1.13 on 2023-09-10 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_merge_20210325_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Competition name')),
                ('pair_finalists', models.BooleanField(blank=True, default=True, verbose_name='Paired Final')),
                ('results_visible', models.BooleanField(default=False, verbose_name='Publish results')),
                ('comp_roles', models.ManyToManyField(to='core.DanceRole', verbose_name='Dance roles')),
            ],
        ),
        migrations.CreateModel(
            name='PrelimsRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_num', models.IntegerField()),
                ('comp_checked_in', models.BooleanField(default=False, verbose_name='Checked In')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.competition')),
                ('comp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancerole', verbose_name='Dance Role')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Competitor')),
            ],
            options={
                'unique_together': {('comp', 'competitor')},
            },
        ),
        migrations.CreateModel(
            name='PrelimsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('yes', 'Y'), ('maybe', 'Mb'), ('no', '')], default='no', max_length=10)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.competition')),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.prelimsregistration')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comp', 'judge', 'comp_reg')},
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prelims', models.BooleanField(default=False, verbose_name='Judging Prelims')),
                ('finals', models.BooleanField(default=False, verbose_name='Judging Finals')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.competition')),
                ('prelims_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancerole')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('profile', 'comp')},
            },
        ),
    ]
