# Generated by Django 3.1.13 on 2023-07-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20210325_1619'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='dance_roles',
            field=models.ManyToManyField(to='core.DanceRole', verbose_name='Dance roles'),
        ),
    ]
