# Generated by Django 3.1.13 on 2023-07-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_competition_dance_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='dance_roles',
            new_name='comp_roles',
        ),
    ]
