# Generated by Django 3.1.13 on 2023-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_competition_finalists_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelimsregistration',
            name='finalist',
            field=models.BooleanField(default=False, verbose_name='Finalist'),
        ),
    ]
