# Generated by Django 3.1.13 on 2023-07-19 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20210325_1619'),
        ('testapp', '0003_auto_20230719_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelimsregistration',
            name='comp_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dancerole', verbose_name='Dance Role'),
        ),
    ]
