# Generated by Django 3.1.13 on 2023-09-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_prelimsregistration_finalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='stage',
            field=models.CharField(choices=[('r', 'Registration'), ('p', 'Prelims'), ('f', 'Finals')], default='r', max_length=12),
        ),
    ]
