# Generated by Django 3.1.13 on 2023-09-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_competition_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='stage',
            field=models.CharField(choices=[('r', 'Registration'), ('p', 'Prelims'), ('d', 'Draw'), ('f', 'Finals')], default='r', max_length=12),
        ),
    ]
