# Generated by Django 3.1.13 on 2023-07-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20210325_1619'),
        ('testapp', '0004_auto_20230719_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelimsregistration',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='Competitor'),
        ),
    ]
