# Generated by Django 3.1.13 on 2023-07-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20210325_1619'),
        ('testapp', '0005_auto_20230720_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelimsregistration',
            name='comp_checked_in',
            field=models.BooleanField(default=False, verbose_name='Check In'),
        ),
        migrations.AlterUniqueTogether(
            name='prelimsregistration',
            unique_together={('comp', 'competitor')},
        ),
    ]
