# Generated by Django 3.1.13 on 2023-09-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20230912_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelimsregistration',
            name='final_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.prelimsregistration', verbose_name='Partner in final'),
        ),
    ]
