# Generated by Django 3.1.13 on 2023-09-13 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0006_prelimsregistration_final_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='finals_main_judge',
            field=models.BooleanField(default=False, verbose_name='Finals Main Judge'),
        ),
        migrations.AddField(
            model_name='judge',
            name='prelims_main_judge',
            field=models.BooleanField(default=False, verbose_name='Prelims Main Judge'),
        ),
        migrations.CreateModel(
            name='FinalsResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(verbose_name='Place')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.competition')),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.prelimsregistration')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('comp', 'judge', 'comp_reg')},
            },
        ),
    ]
