# Generated by Django 3.1.13 on 2023-07-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20230720_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelimsregistration',
            name='comp_checked_in',
            field=models.BooleanField(default=False, verbose_name='Checked In'),
        ),
    ]
