# Generated by Django 3.1.13 on 2023-09-13 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0053_merge_20210325_1619'),
        ('testapp', '0007_auto_20230913_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrelimsRegistration',
            new_name='Registration',
        ),
        migrations.RenameField(
            model_name='finalsresult',
            old_name='judge',
            new_name='judge_profile',
        ),
        migrations.RenameField(
            model_name='prelimsresult',
            old_name='judge',
            new_name='judge_profile',
        ),
        migrations.AlterUniqueTogether(
            name='finalsresult',
            unique_together={('comp', 'judge_profile', 'comp_reg')},
        ),
        migrations.AlterUniqueTogether(
            name='prelimsresult',
            unique_together={('comp', 'judge_profile', 'comp_reg')},
        ),
    ]
