# Generated by Django 3.1.13 on 2023-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20230913_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsresult',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prelimsresult',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
