# Generated by Django 3.1.13 on 2023-09-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20230914_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='final_heat_order',
            field=models.IntegerField(default=0),
        ),
    ]
