# Generated by Django 3.1.13 on 2023-09-14 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_registration_final_heat_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalsresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prelimsresult',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('comp_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.registration')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.judge')),
            ],
            options={
                'unique_together': {('judge', 'comp_reg')},
            },
        ),
        migrations.RemoveField(
            model_name='finalsresult',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='finalsresult',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='finalsresult',
            name='comp_reg',
        ),
        migrations.RemoveField(
            model_name='finalsresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='finalsresult',
            name='judge_profile',
        ),
        migrations.RemoveField(
            model_name='prelimsresult',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='prelimsresult',
            name='comp',
        ),
        migrations.RemoveField(
            model_name='prelimsresult',
            name='comp_reg',
        ),
        migrations.RemoveField(
            model_name='prelimsresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prelimsresult',
            name='judge_profile',
        ),
        migrations.AddField(
            model_name='finalsresult',
            name='result_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.result'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prelimsresult',
            name='result_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.result'),
            preserve_default=False,
        ),
    ]
