# Generated by Django 3.1.13 on 2023-09-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20230914_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsresult',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finalsresult',
            name='comp_reg',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalsresult',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalsresult',
            name='judge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.judge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prelimsresult',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='prelimsresult',
            name='comp_reg',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prelimsresult',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prelimsresult',
            name='judge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testapp.judge'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='finalsresult',
            unique_together={('judge', 'comp_reg')},
        ),
        migrations.AlterUniqueTogether(
            name='prelimsresult',
            unique_together={('judge', 'comp_reg')},
        ),
        migrations.RemoveField(
            model_name='finalsresult',
            name='result_ptr',
        ),
        migrations.RemoveField(
            model_name='prelimsresult',
            name='result_ptr',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
